### ISSUE TITLE
 Accounts.createUser is not a function

### ISSUE THREAD

**Issue by ralphievolt** [dan335/meteor-accounts-templates#1]
Error found in web console

```
Uncaught TypeError: Accounts.createUser is not a function
```

**Comment by dan335** [comment]
Does "meteor add accounts-password" fix this?

**Comment by ralphievolt** [comment]
It did fix it but the button stayed on the " PLEASE WAIT" state even when the account is already created

**Comment by dan335** [comment]
This package doesn't have reactivity for when the user is logged in.  You should check if the user is logged in, maybe in your router and when they are hide the form or send them to another page.
